modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/samolego/Blacksmiths/issues"
license = "MIT"

[[mods]]
modId = "blacksmiths"
version = "${version}"
displayName = "Blacksmiths"
authors = "samo_lego"
description = '''
A Taterzens addon that brings tool-repairing-guys to Minecraft.
'''
logoFile = "blacksmiths_icon.png"

[[dependencies.blacksmiths]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blacksmiths]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blacksmiths]]
modId = "taterzens"
mandatory = true
versionRange = "[1.6.5,)"
ordering = "AFTER"
side = "BOTH"